#!/bin/sh
#
# helloworld

case $1 in 
start)
	java -jar /opt/helloworld/helloworld-1.0-standalone.jar
	exit $?
	;;
restart|reload|force-reload)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 (start|restart)"
	exit 1
	;;
esac

exit 0